export const FETCHING_INPROGRESS = 'FETCHING_INPROGRESS';
export  const GET_CROP_DETAILS_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';
export const GET_DISEASE_AND_PESTS_DETAILS_SUCCESS = 'GET_DISEASE_AND_PESTS_DETAILS_SUCCESS';
